name: Generate Snake

on:
  workflow_dispatch:    
  schedule:
    - cron: "0 0 * * *" 

jobs:
  generate:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: isaipaucar
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the generated SVG to the output branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated snake svg"
          add: "dist/github-contribution-grid-snake.svg"
          push: true
          branch: output
